# Generated by Django 6.0 on 2026-07-10 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_project_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfessionalDevelopment",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.RemoveField(
            model_name="aboutme",
            name="base_secret_code",
        ),
        migrations.RemoveField(
            model_name="aboutme",
            name="clearance_level",
        ),
        migrations.RemoveField(
            model_name="aboutme",
            name="portal_dream",
        ),
        migrations.RemoveField(
            model_name="aboutme",
            name="sidebar_code",
        ),
    ]
