# Generated by Django 6.0 on 2026-08-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_project_live_url_alter_watchlistitem_genre_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutMe",
        ),
        migrations.DeleteModel(
            name="ProfessionalDevelopment",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
